// website/src/components/Footer.vue
<template>
  <footer id="footer">
    <hr />
    <p class="text-center">
      Copyright &copy; Ronen Lapushner, 2019 - 2020.
      <br />Code available
      <a
        href="https://github.com/ronen25/ronen.xyz"
      >here</a>
      under the AGPL 3+ license.
    </p>
  </footer>
</template>

<script>
export default {
  name: "Footer"
};
</script>

<style scoped>
#footer {
  min-width: 100%;
  background-color: #35393d;
  color: rgb(252, 252, 252);
  margin-bottom: 0px;
  margin-top: 0px;
  padding-bottom: 10px;
}

a {
  color: lightblue;
}

</style>

// src/components/Footer.tsx
import React from 'react';
import Link from 'next/link';

import GithubIcon from '../assets/github.svg';
import LinkedinIcon from '../assets/linkedin.svg';

const Footer = () => {
  return (
    <footer className='container flex flex-row bg-cornflower-500 fixed bottom-0 p-2'>
      <div className='text-white ml-8 text-4xl align-top'>ronen.xyz</div>
      <ul className='text-white ml-4 mt-2'>
        <li>
          <Link href='/'>
            <a className='hover:font-bold transition hover:text-cyan'>Home</a>
          </Link>
        </li>
        <li>Blog</li>
        <li>Translations</li>
        <li>
          <a
            href='https://github.com/ronen25'
            className='flex flex-row items-center group transition space-x-1'
          >
            <GithubIcon
              width={16}
              height={16}
              fill={'white'}
              className='group-hover:fill-cyan'
            />
            <span className='group-hover:text-cyan group-hover:font-bold'>Github</span>
          </a>
        </li>
        <li>
          <a
            href='https://www.linkedin.com/in/ronen-lapushner/'
            className='flex flex-row items-center group transition space-x-1'
          >
            <LinkedinIcon
              width={16}
              height={16}
              fill={'white'}
              className='group-hover:fill-cyan'
            />
            <span className='group-hover:text-cyan group-hover:font-bold'>LinkedIn</span>
          </a>
        </li>
      </ul>
      <div className='grow'></div>
      <div className='self-end text-white text-sm pr-2'>
        Copyright (c) Ronen Lapushner 2022.
        <br />
        Blog posts and translations are provided under the CC-BY-4.0 license.
      </div>
    </footer>
  );
};

export default Footer;
